server:
  port: 8001

spring:
  cloud:
    gateway:
      routes:
        - id: time_route
          uri: http://localhost:8762
          predicates:
          - Path=/organization/**
          - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]


  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka